<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>4Loginbutton</name>
   <tag></tag>
   <elementGuidId>317f2075-8611-44e5-8b73-3c399c382b41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;loginForm&quot;]/form/div[4]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;loginForm&quot;]/form/div[4]/div/div/input</value>
   </webElementProperties>
</WebElementEntity>
