<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>5.LoginerrorMessage</name>
   <tag></tag>
   <elementGuidId>f3cd85eb-94e3-47b9-9a9e-8cb7abd048c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;viewbagalert&quot;]/center/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;viewbagalert&quot;]/center/strong</value>
   </webElementProperties>
</WebElementEntity>
