<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>7.ForgotPasswordLink</name>
   <tag></tag>
   <elementGuidId>cb299026-c194-418f-a04f-e592ba25ff80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href=&quot;/Account/ForgotPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@href=&quot;/Account/ForgotPassword&quot;]</value>
   </webElementProperties>
</WebElementEntity>
