<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>9.1EmailidAddressdoesnotExist</name>
   <tag></tag>
   <elementGuidId>9ee7023a-21bf-4a08-8e42-ac48d1a590c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;viewbagalert&quot;]/center/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;viewbagalert&quot;]/center/strong</value>
   </webElementProperties>
</WebElementEntity>
