<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>6.1PasswordNot Meet the Requirment</name>
   <tag></tag>
   <elementGuidId>30109acf-3bc7-42e8-89c5-3e42bd11fbba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Password-error']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;Password-error&quot;)[count(. | //span[@id = 'Password-error' and (text() = concat('Password should be 6 to 15 character long with at least one Digit, Lowercase (' , &quot;'&quot; , 'a - z' , &quot;'&quot; , ') and Uppercase (' , &quot;'&quot; , 'A - Z' , &quot;'&quot; , ') character and Special character(Ex: $).') or . = concat('Password should be 6 to 15 character long with at least one Digit, Lowercase (' , &quot;'&quot; , 'a - z' , &quot;'&quot; , ') and Uppercase (' , &quot;'&quot; , 'A - Z' , &quot;'&quot; , ') character and Special character(Ex: $).'))]) = count(//span[@id = 'Password-error' and (text() = concat('Password should be 6 to 15 character long with at least one Digit, Lowercase (' , &quot;'&quot; , 'a - z' , &quot;'&quot; , ') and Uppercase (' , &quot;'&quot; , 'A - Z' , &quot;'&quot; , ') character and Special character(Ex: $).') or . = concat('Password should be 6 to 15 character long with at least one Digit, Lowercase (' , &quot;'&quot; , 'a - z' , &quot;'&quot; , ') and Uppercase (' , &quot;'&quot; , 'A - Z' , &quot;'&quot; , ') character and Special character(Ex: $).'))])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Password-error</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password should be 6 to 15 character long with at least one Digit, Lowercase ('a - z') and Uppercase ('A - Z') character and Special character(Ex: $).</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Password-error&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//span[@id='Password-error']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//section[@id='loginForm']/form/div[6]/div/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register Your Account'])[1]/following::span[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//span/span</value>
   </webElementXpaths>
</WebElementEntity>
