<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>5.LoginerrorMessage</name>
   <tag></tag>
   <elementGuidId>a8bb9990-5c13-4547-9fcc-d6ed614cf2ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;viewbagalert&quot;]/center/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;viewbagalert&quot;]/center/strong</value>
   </webElementProperties>
</WebElementEntity>
