<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>E.3.PurchaseOrders</name>
   <tag></tag>
   <elementGuidId>13f16992-29dd-4f5a-b0c0-7ddff579d2cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;wrapper&quot;]/div/div[4]/section/div/div[1]/div[3]/div/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;wrapper&quot;]/div/div[4]/section/div/div[1]/div[3]/div/span/a</value>
   </webElementProperties>
</WebElementEntity>
