<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>E.4.MenuICon</name>
   <tag></tag>
   <elementGuidId>6d4e6d8f-438f-4a21-86b4-cd14547d18b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;wrapper&quot;]/header/nav/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;wrapper&quot;]/header/nav/a</value>
   </webElementProperties>
</WebElementEntity>
