<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>3.Remberme</name>
   <tag></tag>
   <elementGuidId>bca311f1-0a8e-41bd-bc6b-ac8e1179ee8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;loginForm&quot;]/form/div[3]/div/div/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;loginForm&quot;]/form/div[3]/div/div/label/div</value>
   </webElementProperties>
</WebElementEntity>
