<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10.CurrentpasswordError</name>
   <tag></tag>
   <elementGuidId>60ada143-05ef-46e0-b1a5-dcf344851214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tempdataalert&quot;]/label/b/span/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tempdataalert&quot;]/label/b/span/strong</value>
   </webElementProperties>
</WebElementEntity>
