<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>8.1ConfirmPassword-error</name>
   <tag></tag>
   <elementGuidId>66dd6be5-5cfa-452d-9388-79d20a30b9fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id=&quot;ConfirmPassword-error&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id=&quot;ConfirmPassword-error&quot;]</value>
   </webElementProperties>
</WebElementEntity>
